// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quotes.sql

package storage

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimNextQuoteUpdate = `-- name: ClaimNextQuoteUpdate :one
WITH candidate AS (
    SELECT id
    FROM quote_updates
    WHERE status = 'PENDING'
      AND next_attempt_at <= NOW()
    ORDER BY next_attempt_at, created_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE quote_updates
SET status = 'PROCESSING',
    locked_until = $1,
    attempt_count = attempt_count + 1,
    updated_at = NOW()
WHERE id IN (SELECT id FROM candidate)
RETURNING id, currency_pair, status, rate, error_message, attempt_count, next_attempt_at, locked_until, created_at, updated_at
`

func (q *Queries) ClaimNextQuoteUpdate(ctx context.Context, lockedUntil *time.Time) (QuoteUpdate, error) {
	row := q.db.QueryRow(ctx, claimNextQuoteUpdate, lockedUntil)
	var i QuoteUpdate
	err := row.Scan(
		&i.ID,
		&i.CurrencyPair,
		&i.Status,
		&i.Rate,
		&i.ErrorMessage,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrGetActiveQuoteUpdate = `-- name: CreateOrGetActiveQuoteUpdate :one
INSERT INTO quote_updates (currency_pair, status)
VALUES ($1, 'PENDING')
ON CONFLICT (currency_pair) WHERE status IN ('PENDING', 'PROCESSING')
DO UPDATE SET currency_pair = EXCLUDED.currency_pair
RETURNING id, currency_pair, status, rate, error_message, attempt_count, next_attempt_at, locked_until, created_at, updated_at
`

func (q *Queries) CreateOrGetActiveQuoteUpdate(ctx context.Context, currencyPair string) (QuoteUpdate, error) {
	row := q.db.QueryRow(ctx, createOrGetActiveQuoteUpdate, currencyPair)
	var i QuoteUpdate
	err := row.Scan(
		&i.ID,
		&i.CurrencyPair,
		&i.Status,
		&i.Rate,
		&i.ErrorMessage,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getByID = `-- name: GetByID :one
SELECT id, currency_pair, status, rate, error_message, attempt_count, next_attempt_at, locked_until, created_at, updated_at
FROM quote_updates
WHERE id = $1
`

func (q *Queries) GetByID(ctx context.Context, id uuid.UUID) (QuoteUpdate, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i QuoteUpdate
	err := row.Scan(
		&i.ID,
		&i.CurrencyPair,
		&i.Status,
		&i.Rate,
		&i.ErrorMessage,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestByPair = `-- name: GetLatestByPair :one
SELECT id, currency_pair, status, rate, error_message, attempt_count, next_attempt_at, locked_until, created_at, updated_at
FROM quote_updates
WHERE currency_pair = $1
  AND status = 'SUCCESS'
ORDER BY updated_at DESC
LIMIT 1
`

func (q *Queries) GetLatestByPair(ctx context.Context, currencyPair string) (QuoteUpdate, error) {
	row := q.db.QueryRow(ctx, getLatestByPair, currencyPair)
	var i QuoteUpdate
	err := row.Scan(
		&i.ID,
		&i.CurrencyPair,
		&i.Status,
		&i.Rate,
		&i.ErrorMessage,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markQuoteUpdateFailed = `-- name: MarkQuoteUpdateFailed :one
UPDATE quote_updates
SET status = 'FAILED',
    rate = NULL,
    error_message = $1,
    locked_until = NULL,
    updated_at = NOW()
WHERE id = $2
  AND status = 'PROCESSING'
  AND locked_until > NOW()
RETURNING id, currency_pair, status, rate, error_message, attempt_count, next_attempt_at, locked_until, created_at, updated_at
`

type MarkQuoteUpdateFailedParams struct {
	ErrorMessage pgtype.Text
	ID           uuid.UUID
}

func (q *Queries) MarkQuoteUpdateFailed(ctx context.Context, arg MarkQuoteUpdateFailedParams) (QuoteUpdate, error) {
	row := q.db.QueryRow(ctx, markQuoteUpdateFailed, arg.ErrorMessage, arg.ID)
	var i QuoteUpdate
	err := row.Scan(
		&i.ID,
		&i.CurrencyPair,
		&i.Status,
		&i.Rate,
		&i.ErrorMessage,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markQuoteUpdateSucceeded = `-- name: MarkQuoteUpdateSucceeded :one
UPDATE quote_updates
SET status = 'SUCCESS',
    rate = $1,
    error_message = NULL,
    locked_until = NULL,
    updated_at = NOW()
WHERE id = $2
  AND status = 'PROCESSING'
  AND locked_until > NOW()
RETURNING id, currency_pair, status, rate, error_message, attempt_count, next_attempt_at, locked_until, created_at, updated_at
`

type MarkQuoteUpdateSucceededParams struct {
	Rate pgtype.Numeric
	ID   uuid.UUID
}

func (q *Queries) MarkQuoteUpdateSucceeded(ctx context.Context, arg MarkQuoteUpdateSucceededParams) (QuoteUpdate, error) {
	row := q.db.QueryRow(ctx, markQuoteUpdateSucceeded, arg.Rate, arg.ID)
	var i QuoteUpdate
	err := row.Scan(
		&i.ID,
		&i.CurrencyPair,
		&i.Status,
		&i.Rate,
		&i.ErrorMessage,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const requeueExpiredQuoteUpdates = `-- name: RequeueExpiredQuoteUpdates :execrows
UPDATE quote_updates
SET status = 'PENDING',
    locked_until = NULL,
    next_attempt_at = NOW(),
    updated_at = NOW()
WHERE status = 'PROCESSING'
  AND locked_until < NOW()
`

func (q *Queries) RequeueExpiredQuoteUpdates(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, requeueExpiredQuoteUpdates)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const scheduleQuoteUpdateRetry = `-- name: ScheduleQuoteUpdateRetry :one
UPDATE quote_updates
SET status = 'PENDING',
    error_message = $1,
    locked_until = NULL,
    next_attempt_at = $2,
    updated_at = NOW()
WHERE id = $3
  AND status = 'PROCESSING'
  AND locked_until > NOW()
RETURNING id, currency_pair, status, rate, error_message, attempt_count, next_attempt_at, locked_until, created_at, updated_at
`

type ScheduleQuoteUpdateRetryParams struct {
	ErrorMessage  pgtype.Text
	NextAttemptAt time.Time
	ID            uuid.UUID
}

func (q *Queries) ScheduleQuoteUpdateRetry(ctx context.Context, arg ScheduleQuoteUpdateRetryParams) (QuoteUpdate, error) {
	row := q.db.QueryRow(ctx, scheduleQuoteUpdateRetry, arg.ErrorMessage, arg.NextAttemptAt, arg.ID)
	var i QuoteUpdate
	err := row.Scan(
		&i.ID,
		&i.CurrencyPair,
		&i.Status,
		&i.Rate,
		&i.ErrorMessage,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
