// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storage

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type IdempotencyKey struct {
	Key          string
	RequestHash  string
	UpdateID     uuid.UUID
	ResponseCode int16
	ExpiresAt    time.Time
	CreatedAt    time.Time
}

type OutboxEvent struct {
	ID            int64
	QuoteID       uuid.UUID
	EventType     string
	Payload       []byte
	CreatedAt     time.Time
	PublishedAt   *time.Time
	AttemptCount  int32
	NextAttemptAt time.Time
}

type QuoteUpdate struct {
	ID            uuid.UUID
	CurrencyPair  string
	Status        string
	Rate          pgtype.Numeric
	ErrorMessage  pgtype.Text
	AttemptCount  int32
	NextAttemptAt time.Time
	LockedUntil   *time.Time
	LeaseToken    *uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
