// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quotes.sql

package storage

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimNextQuoteUpdate = `-- name: ClaimNextQuoteUpdate :one
WITH candidate AS (
    SELECT id
    FROM quote_updates
    WHERE status = 'PENDING'
      AND next_attempt_at <= NOW()
    ORDER BY next_attempt_at, created_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE quote_updates
SET status = 'PROCESSING',
    locked_until = $1,
    attempt_count = attempt_count + 1,
    updated_at = NOW()
WHERE id IN (SELECT id FROM candidate)
RETURNING quote_updates.id, quote_updates.currency_pair, quote_updates.status, quote_updates.rate, quote_updates.error_message, quote_updates.attempt_count, quote_updates.next_attempt_at, quote_updates.locked_until, quote_updates.lease_token, quote_updates.created_at, quote_updates.updated_at
`

func (q *Queries) ClaimNextQuoteUpdate(ctx context.Context, lockedUntil *time.Time) (QuoteUpdate, error) {
	row := q.db.QueryRow(ctx, claimNextQuoteUpdate, lockedUntil)
	var i QuoteUpdate
	err := row.Scan(
		&i.ID,
		&i.CurrencyPair,
		&i.Status,
		&i.Rate,
		&i.ErrorMessage,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LockedUntil,
		&i.LeaseToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrGetActiveQuoteUpdate = `-- name: CreateOrGetActiveQuoteUpdate :one
INSERT INTO quote_updates (currency_pair, status)
VALUES ($1, 'PENDING')
ON CONFLICT (currency_pair) WHERE status IN ('PENDING', 'PROCESSING')
DO UPDATE SET currency_pair = EXCLUDED.currency_pair
RETURNING quote_updates.id, quote_updates.currency_pair, quote_updates.status, quote_updates.rate, quote_updates.error_message, quote_updates.attempt_count, quote_updates.next_attempt_at, quote_updates.locked_until, quote_updates.lease_token, quote_updates.created_at, quote_updates.updated_at
`

func (q *Queries) CreateOrGetActiveQuoteUpdate(ctx context.Context, currencyPair string) (QuoteUpdate, error) {
	row := q.db.QueryRow(ctx, createOrGetActiveQuoteUpdate, currencyPair)
	var i QuoteUpdate
	err := row.Scan(
		&i.ID,
		&i.CurrencyPair,
		&i.Status,
		&i.Rate,
		&i.ErrorMessage,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LockedUntil,
		&i.LeaseToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getByID = `-- name: GetByID :one
SELECT quote_updates.id, quote_updates.currency_pair, quote_updates.status, quote_updates.rate, quote_updates.error_message, quote_updates.attempt_count, quote_updates.next_attempt_at, quote_updates.locked_until, quote_updates.lease_token, quote_updates.created_at, quote_updates.updated_at
FROM quote_updates
WHERE id = $1
`

func (q *Queries) GetByID(ctx context.Context, id uuid.UUID) (QuoteUpdate, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i QuoteUpdate
	err := row.Scan(
		&i.ID,
		&i.CurrencyPair,
		&i.Status,
		&i.Rate,
		&i.ErrorMessage,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LockedUntil,
		&i.LeaseToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT idempotency_keys.key, idempotency_keys.request_hash, idempotency_keys.update_id, idempotency_keys.response_code, idempotency_keys.expires_at, idempotency_keys.created_at
FROM idempotency_keys
WHERE key = $1
  AND expires_at > NOW()
`

func (q *Queries) GetIdempotencyKey(ctx context.Context, key string) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, key)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.RequestHash,
		&i.UpdateID,
		&i.ResponseCode,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestByPair = `-- name: GetLatestByPair :one
SELECT quote_updates.id, quote_updates.currency_pair, quote_updates.status, quote_updates.rate, quote_updates.error_message, quote_updates.attempt_count, quote_updates.next_attempt_at, quote_updates.locked_until, quote_updates.lease_token, quote_updates.created_at, quote_updates.updated_at
FROM quote_updates
WHERE currency_pair = $1
  AND status = 'SUCCESS'
ORDER BY updated_at DESC
LIMIT 1
`

func (q *Queries) GetLatestByPair(ctx context.Context, currencyPair string) (QuoteUpdate, error) {
	row := q.db.QueryRow(ctx, getLatestByPair, currencyPair)
	var i QuoteUpdate
	err := row.Scan(
		&i.ID,
		&i.CurrencyPair,
		&i.Status,
		&i.Rate,
		&i.ErrorMessage,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LockedUntil,
		&i.LeaseToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockIdempotencyKey = `-- name: LockIdempotencyKey :exec
SELECT pg_advisory_xact_lock(hashtext($1))
`

func (q *Queries) LockIdempotencyKey(ctx context.Context, hashtext string) error {
	_, err := q.db.Exec(ctx, lockIdempotencyKey, hashtext)
	return err
}

const markQuoteUpdateFailed = `-- name: MarkQuoteUpdateFailed :one
UPDATE quote_updates
SET status = 'FAILED',
    rate = NULL,
    error_message = $1,
    locked_until = NULL,
    updated_at = NOW()
WHERE id = $2
  AND status = 'PROCESSING'
  AND locked_until > NOW()
RETURNING quote_updates.id, quote_updates.currency_pair, quote_updates.status, quote_updates.rate, quote_updates.error_message, quote_updates.attempt_count, quote_updates.next_attempt_at, quote_updates.locked_until, quote_updates.lease_token, quote_updates.created_at, quote_updates.updated_at
`

type MarkQuoteUpdateFailedParams struct {
	ErrorMessage pgtype.Text
	ID           uuid.UUID
}

func (q *Queries) MarkQuoteUpdateFailed(ctx context.Context, arg MarkQuoteUpdateFailedParams) (QuoteUpdate, error) {
	row := q.db.QueryRow(ctx, markQuoteUpdateFailed, arg.ErrorMessage, arg.ID)
	var i QuoteUpdate
	err := row.Scan(
		&i.ID,
		&i.CurrencyPair,
		&i.Status,
		&i.Rate,
		&i.ErrorMessage,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LockedUntil,
		&i.LeaseToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markQuoteUpdateSucceeded = `-- name: MarkQuoteUpdateSucceeded :one
UPDATE quote_updates
SET status = 'SUCCESS',
    rate = $1,
    error_message = NULL,
    locked_until = NULL,
    updated_at = NOW()
WHERE id = $2
  AND status = 'PROCESSING'
  AND locked_until > NOW()
RETURNING quote_updates.id, quote_updates.currency_pair, quote_updates.status, quote_updates.rate, quote_updates.error_message, quote_updates.attempt_count, quote_updates.next_attempt_at, quote_updates.locked_until, quote_updates.lease_token, quote_updates.created_at, quote_updates.updated_at
`

type MarkQuoteUpdateSucceededParams struct {
	Rate pgtype.Numeric
	ID   uuid.UUID
}

func (q *Queries) MarkQuoteUpdateSucceeded(ctx context.Context, arg MarkQuoteUpdateSucceededParams) (QuoteUpdate, error) {
	row := q.db.QueryRow(ctx, markQuoteUpdateSucceeded, arg.Rate, arg.ID)
	var i QuoteUpdate
	err := row.Scan(
		&i.ID,
		&i.CurrencyPair,
		&i.Status,
		&i.Rate,
		&i.ErrorMessage,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LockedUntil,
		&i.LeaseToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const requeueExpiredQuoteUpdates = `-- name: RequeueExpiredQuoteUpdates :execrows
UPDATE quote_updates
SET status = 'PENDING',
    locked_until = NULL,
    next_attempt_at = NOW(),
    updated_at = NOW()
WHERE status = 'PROCESSING'
  AND locked_until < NOW()
`

func (q *Queries) RequeueExpiredQuoteUpdates(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, requeueExpiredQuoteUpdates)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const scheduleQuoteUpdateRetry = `-- name: ScheduleQuoteUpdateRetry :one
UPDATE quote_updates
SET status = 'PENDING',
    error_message = $1,
    locked_until = NULL,
    next_attempt_at = $2,
    updated_at = NOW()
WHERE id = $3
  AND status = 'PROCESSING'
  AND locked_until > NOW()
RETURNING quote_updates.id, quote_updates.currency_pair, quote_updates.status, quote_updates.rate, quote_updates.error_message, quote_updates.attempt_count, quote_updates.next_attempt_at, quote_updates.locked_until, quote_updates.lease_token, quote_updates.created_at, quote_updates.updated_at
`

type ScheduleQuoteUpdateRetryParams struct {
	ErrorMessage  pgtype.Text
	NextAttemptAt time.Time
	ID            uuid.UUID
}

func (q *Queries) ScheduleQuoteUpdateRetry(ctx context.Context, arg ScheduleQuoteUpdateRetryParams) (QuoteUpdate, error) {
	row := q.db.QueryRow(ctx, scheduleQuoteUpdateRetry, arg.ErrorMessage, arg.NextAttemptAt, arg.ID)
	var i QuoteUpdate
	err := row.Scan(
		&i.ID,
		&i.CurrencyPair,
		&i.Status,
		&i.Rate,
		&i.ErrorMessage,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LockedUntil,
		&i.LeaseToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertIdempotencyKey = `-- name: UpsertIdempotencyKey :one
INSERT INTO idempotency_keys (key, request_hash, update_id, response_code, expires_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (key) DO UPDATE
SET request_hash = EXCLUDED.request_hash,
    update_id = EXCLUDED.update_id,
    response_code = EXCLUDED.response_code,
    expires_at = EXCLUDED.expires_at,
    created_at = NOW()
RETURNING idempotency_keys.key, idempotency_keys.request_hash, idempotency_keys.update_id, idempotency_keys.response_code, idempotency_keys.expires_at, idempotency_keys.created_at
`

type UpsertIdempotencyKeyParams struct {
	Key          string
	RequestHash  string
	UpdateID     uuid.UUID
	ResponseCode int16
	ExpiresAt    time.Time
}

func (q *Queries) UpsertIdempotencyKey(ctx context.Context, arg UpsertIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, upsertIdempotencyKey,
		arg.Key,
		arg.RequestHash,
		arg.UpdateID,
		arg.ResponseCode,
		arg.ExpiresAt,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.RequestHash,
		&i.UpdateID,
		&i.ResponseCode,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
