// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for UpdateQuoteDetailsResponseStatus.
const (
	FAILED     UpdateQuoteDetailsResponseStatus = "FAILED"
	PENDING    UpdateQuoteDetailsResponseStatus = "PENDING"
	PROCESSING UpdateQuoteDetailsResponseStatus = "PROCESSING"
	SUCCESS    UpdateQuoteDetailsResponseStatus = "SUCCESS"
)

// Valid indicates whether the value is a known member of the UpdateQuoteDetailsResponseStatus enum.
func (e UpdateQuoteDetailsResponseStatus) Valid() bool {
	switch e {
	case FAILED:
		return true
	case PENDING:
		return true
	case PROCESSING:
		return true
	case SUCCESS:
		return true
	default:
		return false
	}
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error Description of the error that occurred
	//
	// Example: unsupported currency pair: only EUR, USD, MXN are allowed
	Error string `json:"error"`
}

// LatestQuoteResponse defines model for LatestQuoteResponse.
type LatestQuoteResponse struct {
	// CurrencyPair Example: EUR/MXN
	CurrencyPair string `json:"currency_pair"`

	// Rate Example: 21.42
	Rate float64 `json:"rate"`

	// UpdatedAt Example: 2026-09-10T12:00:00Z
	UpdatedAt time.Time `json:"updated_at"`
}

// RefreshQuoteRequest defines model for RefreshQuoteRequest.
type RefreshQuoteRequest struct {
	// CurrencyPair Currency pair in ISO 4217 format. Supported pairs are configured by the service
	//
	// Example: EUR/MXN
	CurrencyPair string `json:"currency_pair"`
}

// RefreshQuoteResponse defines model for RefreshQuoteResponse.
type RefreshQuoteResponse struct {
	// UpdateId Unique background task identifier
	//
	// Example: 9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d
	UpdateId openapi_types.UUID `json:"update_id"`
}

// UpdateQuoteDetailsResponse defines model for UpdateQuoteDetailsResponse.
type UpdateQuoteDetailsResponse struct {
	// CreatedAt Time when the refresh task was created (UTC)
	//
	// Example: 2026-09-10T11:59:00Z
	CreatedAt time.Time `json:"created_at"`

	// CurrencyPair Example: EUR/MXN
	CurrencyPair string `json:"currency_pair"`

	// ErrorMessage Error description (when status is FAILED)
	ErrorMessage *string `json:"error_message,omitempty"`

	// Id Example: 9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d
	Id openapi_types.UUID `json:"id"`

	// Rate Currency pair exchange rate (when status is SUCCESS)
	//
	// Example: 21.42
	Rate *float64 `json:"rate,omitempty"`

	// Status Current update execution status
	//
	// Example: SUCCESS
	Status UpdateQuoteDetailsResponseStatus `json:"status"`

	// UpdatedAt Exchange rate update time (UTC)
	//
	// Example: 2026-09-10T12:00:00Z
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// UpdateQuoteDetailsResponseStatus Current update execution status
//
// Example: SUCCESS
type UpdateQuoteDetailsResponseStatus string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// GetLatestQuoteParams defines parameters for GetLatestQuote.
type GetLatestQuoteParams struct {
	// Pair Currency pair (for example, EUR/MXN, USD/EUR)
	Pair string `form:"pair" json:"pair"`
}

// RefreshQuoteParams defines parameters for RefreshQuote.
type RefreshQuoteParams struct {
	// IdempotencyKey A client-generated unique key. Repeating a request with the same key and identical body returns the same update_id
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// RefreshQuoteJSONRequestBody defines body for RefreshQuote for application/json ContentType.
type RefreshQuoteJSONRequestBody = RefreshQuoteRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetLatestQuote Get the latest current quote value
	// (GET /quotes/latest)
	GetLatestQuote(ctx echo.Context, params GetLatestQuoteParams) error
	// RefreshQuote Request for quote refresh
	// (POST /quotes/refresh)
	RefreshQuote(ctx echo.Context, params RefreshQuoteParams) error
	// GetQuoteUpdateByID Get the quote update result by ID
	// (GET /quotes/updates/{id})
	GetQuoteUpdateByID(ctx echo.Context, id openapi_types.UUID) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetLatestQuote converts echo context to params.
func (w *ServerInterfaceWrapper) GetLatestQuote(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLatestQuoteParams
	// ------------- Required query parameter "pair" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "pair", ctx.QueryParams(), &params.Pair, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter pair: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetLatestQuote(ctx, params)
	return err
}

// RefreshQuote converts echo context to params.
func (w *ServerInterfaceWrapper) RefreshQuote(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params RefreshQuoteParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Idempotency-Key, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Idempotency-Key: %s", err))
		}

		params.IdempotencyKey = IdempotencyKey
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter Idempotency-Key is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RefreshQuote(ctx, params)
	return err
}

// GetQuoteUpdateByID converts echo context to params.
func (w *ServerInterfaceWrapper) GetQuoteUpdateByID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetQuoteUpdateByID(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(options.BaseURL+"/quotes/refresh", wrapper.RefreshQuote, options.OperationMiddlewares["refreshQuote"]...)
	router.GET(options.BaseURL+"/quotes/updates/:id", wrapper.GetQuoteUpdateByID, options.OperationMiddlewares["getQuoteUpdateByID"]...)
	router.GET(options.BaseURL+"/quotes/latest", wrapper.GetLatestQuote, options.OperationMiddlewares["getLatestQuote"]...)

}

type GetLatestQuoteRequestObject struct {
	Params GetLatestQuoteParams
}

type GetLatestQuoteResponseObject interface {
	VisitGetLatestQuoteResponse(w http.ResponseWriter) error
}

type GetLatestQuote200JSONResponse LatestQuoteResponse

func (response GetLatestQuote200JSONResponse) VisitGetLatestQuoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetLatestQuote400JSONResponse ErrorResponse

func (response GetLatestQuote400JSONResponse) VisitGetLatestQuoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetLatestQuote404JSONResponse ErrorResponse

func (response GetLatestQuote404JSONResponse) VisitGetLatestQuoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetLatestQuote500JSONResponse ErrorResponse

func (response GetLatestQuote500JSONResponse) VisitGetLatestQuoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshQuoteRequestObject struct {
	Params RefreshQuoteParams
	Body   *RefreshQuoteJSONRequestBody
}

type RefreshQuoteResponseObject interface {
	VisitRefreshQuoteResponse(w http.ResponseWriter) error
}

type RefreshQuote202JSONResponse RefreshQuoteResponse

func (response RefreshQuote202JSONResponse) VisitRefreshQuoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshQuote400JSONResponse ErrorResponse

func (response RefreshQuote400JSONResponse) VisitRefreshQuoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshQuote409JSONResponse ErrorResponse

func (response RefreshQuote409JSONResponse) VisitRefreshQuoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshQuote500JSONResponse ErrorResponse

func (response RefreshQuote500JSONResponse) VisitRefreshQuoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetQuoteUpdateByIDRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetQuoteUpdateByIDResponseObject interface {
	VisitGetQuoteUpdateByIDResponse(w http.ResponseWriter) error
}

type GetQuoteUpdateByID200JSONResponse UpdateQuoteDetailsResponse

func (response GetQuoteUpdateByID200JSONResponse) VisitGetQuoteUpdateByIDResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetQuoteUpdateByID400JSONResponse ErrorResponse

func (response GetQuoteUpdateByID400JSONResponse) VisitGetQuoteUpdateByIDResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetQuoteUpdateByID404JSONResponse ErrorResponse

func (response GetQuoteUpdateByID404JSONResponse) VisitGetQuoteUpdateByIDResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetQuoteUpdateByID500JSONResponse ErrorResponse

func (response GetQuoteUpdateByID500JSONResponse) VisitGetQuoteUpdateByIDResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetLatestQuote Get the latest current quote value
	// (GET /quotes/latest)
	GetLatestQuote(ctx context.Context, request GetLatestQuoteRequestObject) (GetLatestQuoteResponseObject, error)
	// RefreshQuote Request for quote refresh
	// (POST /quotes/refresh)
	RefreshQuote(ctx context.Context, request RefreshQuoteRequestObject) (RefreshQuoteResponseObject, error)
	// GetQuoteUpdateByID Get the quote update result by ID
	// (GET /quotes/updates/{id})
	GetQuoteUpdateByID(ctx context.Context, request GetQuoteUpdateByIDRequestObject) (GetQuoteUpdateByIDResponseObject, error)
}

type StrictHandlerFunc func(ctx echo.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetLatestQuote operation middleware
func (sh *strictHandler) GetLatestQuote(ctx echo.Context, params GetLatestQuoteParams) error {
	var request GetLatestQuoteRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetLatestQuote(ctx.Request().Context(), request.(GetLatestQuoteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLatestQuote")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetLatestQuoteResponseObject); ok {
		return validResponse.VisitGetLatestQuoteResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// RefreshQuote operation middleware
func (sh *strictHandler) RefreshQuote(ctx echo.Context, params RefreshQuoteParams) error {
	var request RefreshQuoteRequestObject

	request.Params = params

	var body RefreshQuoteJSONRequestBody
	var err error
	if binder, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = binder.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RefreshQuote(ctx.Request().Context(), request.(RefreshQuoteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RefreshQuote")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RefreshQuoteResponseObject); ok {
		return validResponse.VisitRefreshQuoteResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetQuoteUpdateByID operation middleware
func (sh *strictHandler) GetQuoteUpdateByID(ctx echo.Context, id openapi_types.UUID) error {
	var request GetQuoteUpdateByIDRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetQuoteUpdateByID(ctx.Request().Context(), request.(GetQuoteUpdateByIDRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetQuoteUpdateByID")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetQuoteUpdateByIDResponseObject); ok {
		return validResponse.VisitGetQuoteUpdateByIDResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zFh/b9s4Ev0qA94C2wXkWHacX/ovG+cWxnWzPScGFlvkAkoc2WwkUiGpJELg734gKVuS7SQtkKb9z7JI",
	"aubNvDdPeiKJzAspUBhNoidSUEVzNKjc1YRhXkiDIqn+g5X9h6FOFC8Ml4JE5BSSjKMwvTkKVNQgg1Lw",
	"uxLhFqs9mGKB1HAxBwoK70rUBh64WYBZIGiau2VABQPOUBie0AxiySpQaEoldLOuLBg1eMMZCQg+0rzI",
	"kERkgDRN0pNBL8TksDdKj2nvGA9PevQ4HeLh6DBOj4ckINyGukDKUJGACJrbva3Ueja3gNgIuUJGIqNK",
	"DIhOFphTm3ROHz+imJsFiYYHBwHJuVhdDw4DYqrCnqiN4mJOlsvlaq/D8FwpqaaoCyk0OoiVLFAZju42",
	"2tvbyI6bK5CpA8KtBLOgBmSSlMqG2kajFLosCqlsFdxtkVRQUK4ikCKr4Hw2DWB2OQ7gz78vgCoEmmXy",
	"wZ2ymUIbjc91jNfrZTL+gokhy4B8pAa1+W8pDT6f4iqYGxuMy3kd8/ls2v/z7wsSkIIag8qm/r/Pp71/",
	"rp/2l/3Vj1+2IwyIbbfOYcPB3mgYkFSqnBoSESbLOMNmqyjzGJXd6ruJ3dhl7WiG4fCwF570BuHVYBiF",
	"YRSG/5D2idRgz/AcX0Wsm3IdbOfBu9CcYqpQL2o4HV++As1u45y1Kw9cwOTyLxgNB0fg09iDy3WX2CXa",
	"dUIiRcrnpUIGceVph+qeJ9jpsKZaLUYcdfhw9M2VfBG511F6rukaxdiCaOYlKqbJ7VzJUjAwVN/WGpRy",
	"pxJN0ifxgGE8Yr39+Ij1RjFlvZOYsd4wDtlRvM+S+JC1m6Qs+euMaqLbleHM3XUJjtFQnukXyKWw1cvd",
	"RK94jvCwQOEqqjxuPtkHqqHeCh9mV2e/dXJuE2EQHZx8AxGC70R3p0E3OWpN57idqlNZaP0HH1zi2lBT",
	"auAa/n06+Xg+tnmKMsuolYZa6Lee5ZvmrVugkayXGIuPyYKKOYJdvJXE5ezs7PzyslOtZ3XvmTwbHfTn",
	"PheRqacu4CMmpcO03hAQFGVu+/jT+cV4cvEHCcin6V82Mn9Rh0kC4lG3Xd7A2dzdQqirzBsl7iBTx2ab",
	"8JUGfk3JX2mHDea6ym7K+xqXFhu3iW2P4iKV26lderG1Em29j+J471yTYD5Pe7Ee6XdWF+zDDDcu2XUD",
	"OcWA1WGnnyYkIPeotH/IYC/cCy3IskBBC04isr8X7u17Ni5cH/T94f3MzXX7zxx3lGLa8me51AYUJrZh",
	"NL23Y0WtcnGDpMDEquqGKSEuDkXtiRNGIvIHmpabcEE1VvTzy6T5YB9WVz+AWmWc2emfz6a/rTzgXYmq",
	"aizgajY/6/t2Cddmd1zbA7w4OwSHYehkWQqDwkFHiyLjiUu0/0Xb6J9az/hFYUoi8q9+48P7tXvs73JX",
	"rou6WPhlvi8gtQPNVnn0hoF0PeyOEK4WCL9aPH+FddncjBHSQEG1RgZSwYJqoAK4uKcZZ7Uj8cGO3jVY",
	"a34VgpA1m3Z068o/uX8rbTCHCl2wB++J7ETYOUkzR2tU4DY4VdJlnlNVeeq4MD1ra56tGuKeZiW6DSty",
	"10bAeQmpd9D7NEmwMBpol7IB3JVYoivhSn6pvg2cTrVf2bbtVJfqbQe3TfRdcDVL+hvvpJ6Aziv/Lln1",
	"ZoXZ5cWX3WFg5WK5Rf/hdwrhZfJ1zJ2lWYzWOJRJglqnZZZVQF1V0dEOCiXtnXrsjt63oz37V18EvApY",
	"eXj2DdbHePK+erbxhcDJGc0UUlZBaQXNfcqgwHiaoiPcKqPYNuLPKBTTBvJaHVZa0NYHz23df+Js+VUW",
	"IOn6Re+GAu8DgsbFeLe2a/C7FvdvPb9Xk/Frw3/WiA/MZm69m+/WxjTj3Tm1rxnub/SG9z2dwAtvhDta",
	"oY2PNZw2bnvnRzHd1uiHDXv3trv+6Lge75Px2p+sLdNPO9g9V2sSKdRlZiCuYDKuvza6EzxTSpWRiCyM",
	"KaJ+P5MJzRZSm+g4PA77tOD9+wFZXi//HwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
